### ISSUE TITLE
checklist.md

### ISSUE THREAD

**Issue by OliveChao** [frontlinesms/industry-signup-pages#2]
# Campaign Site Visual Outlook
- [ ] Header background image
- [ ] Info-graphic
- [ ] Getting started content
- [ ] Sign up form background image
- [ ] Heading for the sign up form
- [ ] Text on the submit button in the sign up form
- [ ] Content after the sign up form before the footer
- [ ] Footer background image
- [ ] Content on the left side of the footer, the first button's text
- [ ] Content on the right side of the footer
# HTML Validation for the Campaign Site
- [ ] Change the title tag to the appropriate one
- [ ] Change the css link to the appropriate one
- [ ] Change the industry value to the appropriate one
- [ ] Ensure the script to the success page points to the appropriate success.html file
# Success Campaign Page Visual Outlook
- [ ] check the Success message is appropriate to the campaign site
- [ ] "back to the site" text
- [ ] footer Background Image
- [ ] Content on the right side of the Footer
- [ ] Content on the left side of the Footer, first button
# HTML Validation for the Success Campaign Page
- [ ] Change the title tag to the appropriate one
- [ ] Change the css link to the appropriate one
- [ ] Change the "back to site" url to the appropriate one
